name: "Docker Stack Deploy"

on:
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Stack Deploy"
        uses: cssnr/stack-deploy-action@v1
        with:
          name: "stack-name"
          file: "docker-compose.yaml"
          host: ${{ secrets.DOCKER_HOST }}
          user: ${{ secrets.DOCKER_USER }}
          port: 22 # 22 is default, you can remove or change this
          pass: ${{ secrets.DOCKER_PASS }} # not needed with ssh_key
          ssh_key: ${{ secrets.DOCKER_SSH_KEY }} # not needed with pass
